export const START_FETCHING = "START_FETCHING";
export const DATA_FETCHED = "DATA_FETCHED";
// posts
export const START_FETCHING_POSTS = "START_FETCHING_POSTS";
export const POST_FETCHED = "POST_FETCHED";
// comment
export const START_FETCHING_COMMENTS = "START_FETCHING_COMMENTS";
export const COMMENTS_FETCHED = "COMMENTS_FETCHED";
